### ISSUE TITLE
Tag not firing - Error on writing to data layer.

### ISSUE THREAD

**Issue by emilefyon** [avoy18/hubspot-cookie-banner-gtm#12]
Hello,

I followed the steps provided here in the documentation : https://avoy.me/blog/hubspot-cmp

When doing a preview of my website, I see that the tag fails to trigger.
When looking into the errors, here is the error message:

`Tag Hubspot CMP failed write_data_layer permission check. Prohibited write to data layer variable: ads_data_redaction.`

**Below the screenshots**:

![image](https://github.com/user-attachments/assets/2bcc38fb-24a5-4420-86b5-7ef3a78c75b2)

![image](https://github.com/user-attachments/assets/d1e93ef4-229a-4e5f-8813-28ed1a3803cd)

**Comment by avoy18** [comment]
Hey @emilefyon thanks for reaching out! 

I've actually made a fix for this, but having a hard time updating the live template. In the meantime, you can download the template.tpl file from the main branch and import it manually in the tag manager. 

Let me know if that helps!

**Comment by avoy18** [comment]
@emilefyon Update: the new version is also now available in the gallery. Update it in your tag manager and it should fix this issue!

**Comment by avoy18** [comment]
Hey @emilefyon did you get a chance to try the updated version yet?
