### ISSUE TITLE
 Include wait_for_update and ad_user_data in the setDefaultConsent Call

### ISSUE THREAD

**Issue by rush1818** [avoy18/hubspot-cookie-banner-gtm#2]
When reviewing your template, we've noticed that the `setDefaultConsentState` call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This option is required to be set for any asynchronous consent management script load to delay tag execution.

Additionally, we've noticed that some [required consent types](https://support.google.com/tagmanager/answer/13802165) are missing from the consent commands. Please ensure that your template sets the following consent types:
* `ad_storage`
* `ad_user_data`
* `ad_personalization`
* `analytics_storage`

**Comment by avoy18** [comment]
@rush1818 should be good now. Fixed in this PR: https://github.com/avoy18/hubspot-cookie-banner-gtm/pull/5

**Comment by avoy18** [comment]
@rush1818 let me know if there is anything else that needs to be changed!
