### ISSUE TITLE
[Recommendation] Specify region in the consent settings

### ISSUE THREAD

**Issue by rush1818** [avoy18/hubspot-cookie-banner-gtm#6]
While reviewing your template we noticed that `region` is not set in the consent settings. You may want to consider configuring regions as well. See additional information in https://developers.google.com/tag-platform/tag-manager/templates/consent-apis

**Comment by avoy18** [comment]
@rush1818 This is certainly in my plans to make but I thought I would start simple. Is this a blocker for publishing the template in the gallery?

**Comment by avoy18** [comment]
@rush1818 This is now added! https://github.com/avoy18/hubspot-cookie-banner-gtm/pull/7

Please let me know if anything else is needed before the template can be published!

Cheers.

**Comment by avoy18** [comment]
@rush1818 Just following up to make sure you saw my message above!

**Comment by rush1818** [comment]
Thanks, I will review it again later this week.

**Comment by avoy18** [comment]
Hey @rush1818 I see that you've closed the issue. What are the next steps for publishing my template to the gallery?

**Comment by rush1818** [comment]
@avoy18 - it didn't go through completely as it is failing parsing. Could you take a look at your template?

https://tagmanager.google.com/gallery/#/template/avoy18/hubspot-cookie-banner-gtm/status

**Comment by avoy18** [comment]
> @avoy18 - it didn't go through completely as it is failing parsing. Could you take a look at your template?
> 
> 
> 
> https://tagmanager.google.com/gallery/#/template/avoy18/hubspot-cookie-banner-gtm/status

Hey! I'll take a look and get back to you in a few days.

**Comment by avoy18** [comment]
Hi @rush1818 do you have any recommendations on how to validate the template code? 

When I import the template into gtm I don't get any errors. The error in the template gallery is also not descriptive, so I am not even sure what to change...

**Comment by rush1818** [comment]
I see you recently updated the template code. Could you update the metadata file following [these instructions](https://developers.google.com/tag-platform/tag-manager/templates/gallery?sjid=2173096938773478178-NC#update_your_template) and try again?

**Comment by avoy18** [comment]
@rush1818 thanks for the tip. Updated!

**Comment by avoy18** [comment]
Hi @rush1818, I've recently made an update to my template but can't pass the template parsing: https://tagmanager.google.com/gallery/#/template/avoy18/hubspot-cookie-banner-gtm/status

It keeps telling me there is an issue parsing my template. I've re-exported it a bunch of times, updated the metadata file too, but it wont go away.

Is there any kind of testing tool that can help with this? I am honestly not sure what else I can do at this point.
